---
title: "Annunziata DSP Analysis for Protein Panel"
output: html_document
date: "2024-02-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_knit$set(root.dir = '/rstudio-files/ccr-dceg-data/users/ned/DSPWorkflow')

# Increase the time out for downloading the DSP package
options(timeout = max(300, getOption("timeout")))
```

## Install DSP Workflow from github

```{r}

#install.packages("devtools")

library(devtools)

load_all()

#install_github("NIDAP-Community/DSPWorkflow", ref = "protein_panel")
```

## Load the test data

``` {r Load Data, echo=TRUE}
# Create a folder to hold the test data. 
# Below we have designated the folder 'test_data'

# Set paths for downloading dcc files
#downloads.path <- "test_data/Human_Kidney/downloaded/"
#tar.file.name <- "kidney_dccs.tar.gz"
#full.tar.path <- paste0(downloads.path,tar.file.name)

# Check if dcc files were previously downloaded
#if (!file.exists(full.tar.path)) {
  
  # Download dcc files and place in data folder
#  data.url <- "http://hpc.nih.gov/~CCBR/DSPWorkflow/kidney_dccs.tar.gz"
#  download.file(data.url, full.tar.path)
#  untar(full.tar.path, exdir = downloads.path)
#}

library(readxl)

project.folder.path <- "/rstudio-files/ccr-dceg-data/users/ned/CPTR/CPTR-6 Annunziata/CPTR_6_DSP_Annunziata/"

dcc.files <- dir(
  file.path(paste0(project.folder.path, "dccs")),
  pattern = ".dcc$",
  full.names = TRUE,
  recursive = TRUE
)

pkc.files <- c(paste0(project.folder.path, "Mm_P_NGS_Core_v1.0.pkc"),
               paste0(project.folder.path, "Mm_P_NGS_ImmuneActivation_v1.0.pkc"), 
               paste0(project.folder.path, "Mm_P_NGS_ImmuneCellTyping_v1.0.pkc"), 
               paste0(project.folder.path, "Mm_P_NGS_Myeloid_v1.0.pkc"))
pheno.data.file <- paste0(project.folder.path, "CPTR6_Annunziata_annotation.xlsx")

annotation.df <- read_excel("/rstudio-files/ccr-dceg-data/users/ned/CPTR/CPTR-6 Annunziata/CPTR_6_DSP_Annunziata/CPTR6_Annunziata_annotation.xlsx")
```

# Run the first step of the DSP Workflow package

# Study Design

```{r Study Design, echo=TRUE}

# Save the output from the study design function into a list
sdesign.list <- studyDesign(dcc.files = dcc.files, 
                                pkc.files = pkc.files,
                                pheno.data.file = pheno.data.file,
                                pheno.data.sheet = "Annotation template",
                                pheno.data.dcc.col.name = "Sample_ID",
                                protocol.data.col.names = c("aoi", "roi"),
                                experiment.data.col.names = c("panel"),
                                slide.name.col = "slide name", 
                                class.col = "treatment", 
                                region.col = "age", 
                                segment.col = "segment",
                                area.col = "area",
                                nuclei.col = "nuclei", 
                                sankey.exclude.slide = FALSE, 
                                segment.id.length = 4, 
                                analyte.type = "protein")

# The output of the study design function is a Geomxset Object and a Plot
# Print out a summary of the object

print(sdesign.list$object)

# Print out the Sankey Plot

print(sdesign.list$sankey.plot)
```

# Custom Sankey

```{r}

object <- sdesign.list$object
lane1 <- "region"
lane2 <- "class"
lane3 <- "Animal #"
lane4 <- "slide_name"
fill_lane <- "class"


#Establish variables for the Sankey plot
x <- id <- y <- n <- NULL

# select the annotations we want to show, use `` to surround column
# names with spaces or special symbols

# Create a count matrix
count.mat <- count(pData(object), 
                   !!as.name(lane1), 
                   !!as.name(lane2), 
                   !!as.name(lane3), 
                   !!as.name(lane4))

# Remove any rows with NA values
na.per.column <- colSums(is.na(count.mat))
na.total.count <- sum(na.per.column)
                                             
if(na.total.count > 0){
  count.mat <- count.mat[!rowSums(is.na(count.mat)),]
  rownames(count.mat) <- 1:nrow(count.mat)
}
 

# Gather the data and plot in order: lane 1, lane 2, ..., lane n
# gather_set_data creates x, id, y, and n fields within sankey.count.data
# Establish the levels of the Sankey
sankey.count.data <- gather_set_data(count.mat, 1:4)

sankey.count.data$x <-
    factor(
      sankey.count.data$x,
      levels = c(as.name(lane1), as.name(lane2), as.name(lane3), as.name(lane4))
    )
    
  # For position of Sankey 100 segment scale
  adjust.scale.pos = 0

# plot Sankey diagram
sankey.plot <-
  ggplot(sankey.count.data,
         aes(
           x,
           id = id,
           split = y,
           value = n
         )) +
  geom_parallel_sets(aes(fill = !!as.name(fill_lane)), alpha = 0.5, axis.width = 0.1) +
  geom_parallel_sets_axes(axis.width = 0.2) +
  geom_parallel_sets_labels(color = "gray",
                            size = 5,
                            angle = 0) +
  theme_classic(base_size = 14) +
  theme(
    legend.position = "bottom",
    axis.ticks.y = element_blank(),
    axis.line = element_blank(),
    axis.text.y = element_blank()
  ) +
  scale_y_continuous(expand = expansion(0)) +
  scale_x_discrete(expand = expansion(0)) +
  labs(x = "", y = "") +
  annotate(
    geom = "segment",
    x = (4.25 - adjust.scale.pos),
    xend = (4.25 - adjust.scale.pos),
    y = 20,
    yend = 120,
    lwd = 2
  ) +
  annotate(
    geom = "text",
    x = (4.19 - adjust.scale.pos),
    y = 70,
    angle = 90,
    size = 5,
    hjust = 0.5,
    label = "100 segments"
  )

print(sankey.plot)

```


## 2. QC Preprocessing:

```{r QC Preprocessing, echo=TRUE}

library(GeomxTools)
library(tibble)
library(dplyr)

results.folder <- "/rstudio-files/ccr-dceg-data/users/ned/CPTR/CPTR-6 Annunziata/CPTR_6_DSP_Annunziata/results/"

# Set the QC flags using the Nanostring defaults
qc.output <-  setSegmentQCFlags(sdesign.list$object, 
                                qcCutoffs = list(
                                  minSegmenReads = 1000, 
                                  percentAligned = 80, 
                                  percentTrimmed = 80, 
                                  percentStitched = 80, 
                                  percentSaturation = 50, 
                                  minNegativeCount = 10,   
                                  maxNTCCount = 60, 
                                  minArea = 16000))

# Review QC table low sequenced AOIs
qc <- protocolData(qc.output)
qc.df <- qc@data
print(qc.df)

# Review control probes
hk.names <- hkNames(qc.output)
print(hk.names)

igg.names <- iggNames(qc.output)
igg.names

fig <- qcProteinSignal(object = qc.output, neg.names = igg.names)

proteinOrder <- qcProteinSignalNames(object = qc.output, neg.names = igg.names)

fig()

# Save the feature plot
feature.plot <- fig()

export.feature.plot <- FALSE
if(export.feature.plot == TRUE){
  ggsave(file.path(paste0(results.folder, "feature_plot.png")), plot = feature.plot, width = 12, height = 10)
}

# Generate a list of flagged segments

## Annotation columns
object <- qc.output
annotation.data <- pData(object)
  

## Annotation column names
annotation.column.names <- colnames(annotation.data)

## Start the list of selected annotation columns
select.annotation.columns <- "segmentID"

## Check if area and nuclei are included
if("area" %in% annotation.column.names){ 
  select.annotation.columns <- c("area", select.annotation.columns)
} 
if("nuclei" %in% annotation.column.names){ 
  select.annotation.columns <- c("nuclei", select.annotation.columns)
}

## The annotation names based on selected columns as a df
## drop = FALSE ensures single column is still a df
select.annotation.data <- annotation.data[, select.annotation.columns, 
                                          drop = FALSE]
select.annotation.data <- rownames_to_column(select.annotation.data, 
                                             var = "SampleID")

# Gather the QC flagged rows

## Gather the qc data
segment.qc.data <- object@protocolData@data

## The nested flag dataframe
flag.columns <- segment.qc.data %>% select(starts_with("QCFlags"))

## Rows with a positive flag
flagged.rows <- flag.columns[rowSums(flag.columns$QCFlags == TRUE) > 0, ]
flagged.rows <- as.data.frame(flagged.rows)
flagged.rows <- rownames_to_column(flagged.rows, var = "SampleID")

# Gather the additional QC data

## Additional QC column names
add.qc.column.names <- c("Raw", 
                         "Trimmed (%)",
                         "Stitched (%)",
                         "Aligned (%)",
                         "Saturated (%)")

## Check for NTC column
if("NTC" %in% colnames(segment.qc.data)){
  add.qc.column.names <- c("NTC", add.qc.column.names)
}

## Additional QC data
add.qc.columns <- segment.qc.data[, add.qc.column.names]
add.qc.columns <- rownames_to_column(add.qc.columns, var = "SampleID")

## Convert single column matrix and dataframes into vectors
## May cause an issue if there is more then one PKC file
matrix.column <- add.qc.columns$NegGeoMean
vector.column <- as.vector(matrix.column)
add.qc.columns$NegGeoMean <- vector.column

add.qc.columns$TrimmedPerc <- sapply(add.qc.columns$`Trimmed (%)`, 
                                     function(x) unname(unlist(x)))
add.qc.columns$TrimmedPerc <- as.vector(add.qc.columns$TrimmedPerc[,1])

add.qc.columns$StitchedPerc <- sapply(add.qc.columns$`Stitched (%)`, 
                                     function(x) unname(unlist(x)))
add.qc.columns$StitchedPerc <- as.vector(add.qc.columns$StitchedPerc[,1])

add.qc.columns$AlignedPerc <- sapply(add.qc.columns$`Aligned (%)`, 
                                     function(x) unname(unlist(x)))
add.qc.columns$AlignedPerc <- as.vector(add.qc.columns$AlignedPerc[,1])

add.qc.columns$SaturatedPerc <- sapply(add.qc.columns$`Saturated (%)`, 
                                     function(x) unname(unlist(x)))
add.qc.columns$SaturatedPerc <- as.vector(add.qc.columns$SaturatedPerc[,1])

## Remove the nested data frames
add.qc.columns <- add.qc.columns[, -which(names(add.qc.columns) == "Trimmed (%)")]
add.qc.columns <- add.qc.columns[, -which(names(add.qc.columns) == "Stitched (%)")]
add.qc.columns <- add.qc.columns[, -which(names(add.qc.columns) == "Aligned (%)")]
add.qc.columns <- add.qc.columns[, -which(names(add.qc.columns) == "Saturated (%)")]

# Create the final QC flag data frame with all additional info

## Merge the annotation, flag, and additional qc data frames
merge.qc.flagged.df <- merge(merge(select.annotation.data, add.qc.columns, 
                                   by = "SampleID"), 
                             flagged.rows, by = "SampleID")

## Reorder columns so that info is next to flag
final.column.order <- c("SampleID", 
                        "segmentID", 
                        "Raw", 
                        "LowReads", 
                        "TrimmedPerc", 
                        "LowTrimmed", 
                        "StitchedPerc", 
                        "LowStitched", 
                        "AlignedPerc", 
                        "LowAligned", 
                        "SaturatedPerc", 
                        "LowSaturation")

## Add NTC, area, and/or nuclei if part of annotation
if("NTC" %in% colnames(segment.qc.data)){ 
  final.column.order <- c(final.column.order, "NTC", "HighNTC")
} 
if("area" %in% annotation.column.names){ 
  final.column.order <- c(final.column.order, "area", "LowArea")
} 
if("nuclei" %in% annotation.column.names){ 
  final.column.order <- c(final.column.order, "nuclei", "LowNuclei")
}

## The final QC flag df
final.flagged.segment.df <- merge.qc.flagged.df[, final.column.order]

## Final renaming of columns
colnames(final.flagged.segment.df)[colnames(final.flagged.segment.df) == "Raw"] <- "RawReadCount"

print(final.flagged.segment.df)

qc.folder <- paste0(project.folder.path, "qc/")

export.qc.flag.summary <- FALSE

if(export.qc.flag.summary == TRUE){
  
  write.csv(qc.df, file = paste0(qc.folder, "CPTR6_QC_flag_summary.csv"))
  
}

```

## 3. Filtering:

```{r Filtering, echo=TRUE}
  
  # Can remove segments based on flags
  # Below is how you would remove segments flagged with low saturation

  # low sequenced ROIs
  lowSaturation <- which(as.data.frame(protocolData(qc.output)[["QCFlags"]])["LowSaturation"] == TRUE)

  # remove low quality ROIs and compare the before and after
  #passedQC <- qc.output[, -lowSaturation]
  #dim(qc.output)
  #dim(passedQC)

```


## 4. Normalization:
  
```{r Normalization, echo=TRUE}

  # Check for best normalization type
  
  norm.factors <- computeNormalizationFactors(qc.output, 
                                              igg.names = igg.names, 
                                              hk.names = hk.names, 
                                              area = "area", 
                                              nuclei = "Nuclei count")
  
  igg.concordance.treatment <- plotConcordance(object = qc.output, 
                                     targetList = igg.names, 
                                     plotFactor = "class")
  
  ggsave(paste0(qc.folder, "concordance.negative.treatment.png"),
         igg.concordance.treatment)
  
  igg.concordance.age <- plotConcordance(object = qc.output, 
                                     targetList = igg.names, 
                                     plotFactor = "region")
  
  ggsave(paste0(qc.folder, "concordance.negative.age.png"),
         igg.concordance.age)
  
  
  
  hk.concordance.treatment <- plotConcordance(object = qc.output, 
                                    targetList = hk.names, 
                                    plotFactor = "class")
  
  ggsave(paste0(qc.folder, "concordance.hk.treatment.png"),
         hk.concordance.treatment)
  
  hk.concordance.age <- plotConcordance(object = qc.output, 
                                    targetList = hk.names, 
                                    plotFactor = "region")
  
  ggsave(paste0(qc.folder, "concordance.hk.age.png"),
         hk.concordance.age)
  
  

  norm.factor.concordance.treatment <- plotNormFactorConcordance(object = qc.output, plotFactor = "class",
                          normfactors = norm.factors)
  
  norm.factor.concordance.age <- plotNormFactorConcordance(object = qc.output, plotFactor = "class",
                          normfactors = norm.factors)
  
  norm.hk <- normalize(qc.output, norm_method="hk", toElt = "hk_norm")
  
  norm.neg <- normalize(qc.output, norm_method="neg", toElt = "neg_norm")
  
  norm.q3 <- normalize(qc.output, norm_method="quant", desiredQuantile = .75, toElt = "q_norm")
  
  
  probe.signal.hk <- qcProteinSignal(object = norm.hk, neg.names = hk.names)
  
  probe.signal.neg <- qcProteinSignal(object = norm.hk, neg.names = igg.names)

  proteinOrder <- qcProteinSignalNames(object = norm.hk, neg.names = igg.names)

  fig()
  
  
  # Export all read count for raw and normalization methods
  
  ## raw
  raw_counts <- as.data.frame(norm.hk@assayData$exprs)
  feature_list <- rownames(raw_counts)
  raw_counts <- cbind("feature" = feature_list, raw_counts)
  
  ## Housekeeping Normalization
  hk.norm_counts <- norm.hk@assayData$hk_norm
  feature_list <- rownames(hk.norm_counts)
  hk.norm_counts <- cbind("feature" = feature_list, hk.norm_counts)
  
  ## Negative Normalization
  neg.norm_counts <- norm.neg@assayData$neg_norm
  feature_list <- rownames(neg.norm_counts)
  neg.norm_counts <- cbind("feature" = feature_list, neg.norm_counts)
  
  ## Q3 Normalization
  q3.norm_counts <- norm.q3@assayData$q_norm
  feature_list <- rownames(q3.norm_counts)
  q3.norm_counts <- cbind("feature" = feature_list, q3.norm_counts)
  
  # Export all count tables
  
  export_counts <- FALSE
  
  if(export_counts == TRUE){
    
    write.csv(raw_counts, 
              file.path(paste0(results.folder, "raw_counts.csv")), 
              row.names = FALSE)

    write.csv(hk.norm_counts, 
              file.path(paste0(results.folder, "hk_norm_counts.csv")), 
              row.names = FALSE)
    
    write.csv(neg.norm_counts, 
              file.path(paste0(results.folder, "neg_norm_counts.csv")), 
              row.names = FALSE)
    
    write.csv(q3.norm_counts, 
              file.path(paste0(results.folder, "q3_norm_counts.csv")), 
              row.names = FALSE)
    
    
  }
  
  
  
```
# Box plots for proteins of interest

```{r}

library(ggplot2)
library(scales)
library(gridExtra)
library(plotly)
library(grid)

# Remove the NTC rows from the annotation
cleaned.annotation.df <- annotation.df[annotation.df$'slide name' != "No Template Control", ]

# Boxplot for Protein targets

# Gather all targets
feature.list = rownames(hk.norm_counts)

# Set up the normalized counts

for(feature in feature.list){
  
  # Grab the counts
  feature.counts <- hk.norm_counts[feature, , drop = FALSE]
  
  # Make the Sample ID as rows
  feature.counts.df <- as.data.frame(t(feature.counts))
  
  # Create a column for the Sample IDs and remove the .dcc
  feature.counts.df$Sample_ID <- rownames(feature.counts.df)
  feature.counts.df$Sample_ID <- gsub("\\.dcc$", "", feature.counts.df$Sample_ID)
  rownames(feature.counts.df) <- NULL
  
  
  # Combine the counts with the annotation based on Sample ID
  feature.barplot.df <- merge(cleaned.annotation.df, feature.counts.df, by = "Sample_ID")
  
  # Convert counts from characater to numeric
  feature.barplot.df[[feature]] <- as.numeric(feature.barplot.df[[feature]])
  
  
  # Create the boxplots for the two age groups, then combine into a single image
  
  feature.barplot.df.old <- feature.barplot.df[feature.barplot.df$age == "old", ]
    
  feature.barplot.df.young <- feature.barplot.df[feature.barplot.df$age == "young", ]
  
  y.scale.max <- max(feature.barplot.df[[feature]]) + 1000
  
  feature.boxplot.old <- ggplot(feature.barplot.df.old, aes(x = treatment, y = !!sym(feature))) + 
    geom_boxplot(notch = FALSE) + 
    ggtitle("Old") + 
    scale_y_continuous(labels = scales::comma) + 
    ylim(0, y.scale.max)
  
  feature.boxplot.young <- ggplot(feature.barplot.df.young, aes(x = treatment, y = !!sym(feature))) + 
    geom_boxplot(notch = FALSE) + 
    ggtitle("Young") + 
    scale_y_continuous(labels = scales::comma) + 
    ylim(0, y.scale.max)
  
  feature.combined.boxplot <- grid.arrange(feature.boxplot.young, feature.boxplot.old, ncol = 2)
  
  title <- textGrob(paste0(feature,  "signal by Age and Treatment"), gp = gpar(fontsize = 20, fontface = "bold"))
  
  final.feature.boxplot <- grid.arrange(title, feature.combined.boxplot, heights = c(0.1, 0.9))
  
  # Replace bad characters
  if(grepl("/", feature)){
    feature <- gsub("/", "_", feature)
  }
  
  export.boxplot <- TRUE
  
  if(export.boxplot == TRUE){
    ggsave(paste0(project.folder.path, "results/", feature, "_boxplot_age.png"), final.feature.boxplot, width = 12, height = 10)
  }
  
}



# Boxplot for Ki-67

# Set up the Ki-67 normalized counts

# Grab the counts
ki67.counts <- hk.norm_counts["Ki-67", , drop = FALSE]

# Make the Sample ID as rows
ki67.counts.df <- as.data.frame(t(ki67.counts))

# Create a column for the Sample IDs and remove the .dcc
ki67.counts.df$Sample_ID <- rownames(ki67.counts.df)
ki67.counts.df$Sample_ID <- gsub("\\.dcc$", "", ki67.counts.df$Sample_ID)
rownames(ki67.counts.df) <- NULL


# Combine the counts with the annotation based on Sample ID
ki67.barplot.df <- merge(cleaned.annotation.df, ki67.counts.df, by = "Sample_ID")

# Convert counts from charcater to numeric
ki67.barplot.df$`Ki_67` <- as.numeric(ki67.barplot.df$`Ki-67`)


# Create the boxplots for the two age groups, then combine into a single image

ki67.barplot.df.old <- ki67.barplot.df[ki67.barplot.df$age == "old", ]
  
ki67.barplot.df.young <- ki67.barplot.df[ki67.barplot.df$age == "young", ]

ki67.boxplot.old <- ggplot(ki67.barplot.df.old, aes(x = treatment, y = Ki_67)) + 
  geom_boxplot(notch = FALSE) + 
  ggtitle("Old") + 
  scale_y_continuous(labels = scales::comma) + 
  ylim(0, 30000)

ki67.bp.old.plotly <- plotly::ggplotly(ki67.boxplot.old)

ki67.boxplot.young <- ggplot(ki67.barplot.df.young, aes(x = treatment, y = Ki_67)) + 
  geom_boxplot(notch = FALSE) + 
  ggtitle("Young") + 
  scale_y_continuous(labels = scales::comma) + 
  ylim(0, 30000)

ki67.combined.boxplot <- grid.arrange(ki67.boxplot.young, ki67.boxplot.old, ncol = 2)

title <- textGrob("Ki-67 signal by Age and Treatment", gp = gpar(fontsize = 20, fontface = "bold"))

final.ki67.boxplot <- grid.arrange(title, ki67.combined.boxplot, heights = c(0.1, 0.9))

grid.draw(final.ki67.boxplot)

export.boxplot <- FALSE

if(export.boxplot == TRUE){
  ggsave(paste0(project.folder.path, "results/ki67_boxplot_age.png"), final.ki67.boxplot, width = 12, height = 10)
}




# Create the boxplot per animal number

ki67.barplot.df$`animal_num` <- as.factor(ki67.barplot.df$`Animal #`)

ki67.boxplot.animal <- ggplot(ki67.barplot.df, aes(x = animal_num, y = Ki_67)) + 
  geom_boxplot(notch = FALSE) + 
  ggtitle("Ki-67 expression per animal") + 
  scale_y_continuous(labels = scales::comma) + 
  ylim(0, 30000)


# Export the boxplot
export.boxplot <- FALSE

if(export.boxplot == TRUE){
  ggsave(paste0(project.folder.path, "results/ki67_boxplot_animal.png"), ki67.boxplot.animal, width = 12, height = 10)
}




# Make the boxplots for CD45

# Set up the normalized counts

# Grab the counts
cd45.counts <- hk.norm_counts["CD45", , drop = FALSE]

# Make the Sample ID as rows
cd45.counts.df <- as.data.frame(t(cd45.counts))

# Create a column for the Sample IDs and remove the .dcc
cd45.counts.df$Sample_ID <- rownames(cd45.counts.df)
cd45.counts.df$Sample_ID <- gsub("\\.dcc$", "", cd45.counts.df$Sample_ID)
rownames(cd45.counts.df) <- NULL


# Combine the counts with the annotation based on Sample ID
cd45.barplot.df <- merge(cleaned.annotation.df, cd45.counts.df, by = "Sample_ID")

cd45.barplot.df$`CD45` <- as.numeric(cd45.barplot.df$`CD45`)

# Create the boxplots for the two age groups, then combine into a single image

cd45.barplot.df.old <- cd45.barplot.df[cd45.barplot.df$age == "old", ]
  
cd45.barplot.df.young <- cd45.barplot.df[cd45.barplot.df$age == "young", ]

cd45.boxplot.old <- ggplot(cd45.barplot.df.old, aes(x = treatment, y = CD45)) + 
  geom_boxplot(notch = FALSE) + 
  ggtitle("Old") + 
  scale_y_continuous(labels = scales::comma) + 
  ylim(0, 30000)

cd45.bp.old.plotly <- plotly::ggplotly(cd45.boxplot.old)

cd45.boxplot.young <- ggplot(cd45.barplot.df.young, aes(x = treatment, y = CD45)) + 
  geom_boxplot(notch = FALSE) + 
  ggtitle("Young") + 
  scale_y_continuous(labels = scales::comma) + 
  ylim(0, 30000)

cd45.combined.boxplot <- grid.arrange(cd45.boxplot.young, cd45.boxplot.old, ncol = 2)

title <- textGrob("CD45 signal by Age and Treatment", gp = gpar(fontsize = 20, fontface = "bold"))

final.cd45.boxplot <- grid.arrange(title, cd45.combined.boxplot, heights = c(0.1, 0.9))

grid.draw(final.cd45.boxplot)

export.boxplot <- FALSE

if(export.boxplot == TRUE){
  ggsave(paste0(project.folder.path, "results/cd45_boxplot_age.png"), final.cd45.boxplot, width = 12, height = 10)
}



# Create the boxplot per animal number

cd45.barplot.df$`animal_num` <- as.factor(cd45.barplot.df$`Animal #`)

cd45.boxplot.animal <- ggplot(cd45.barplot.df, aes(x = animal_num, y = CD45)) + 
  geom_boxplot(notch = FALSE) + 
  ggtitle("CD45 expression per animal") + 
  scale_y_continuous(labels = scales::comma) + 
  ylim(0, 30000)


# Export the boxplot
export.boxplot <- FALSE

if(export.boxplot == TRUE){
  ggsave(paste0(project.folder.path, "results/cd45_boxplot_animal.png"), cd45.boxplot.animal, width = 12, height = 10)
}


# Boxplot for Nuclei count per ROI and Ki-67 expression

ki67.barplot.df$`nuclei` <- as.numeric(ki67.barplot.df$`Nuclei count`)

ki67.barplot.df$animal_roi <- paste0(ki67.barplot.df$`Animal #`, "_", ki67.barplot.df$roi)

# Create a plot labeled for plotly
ki67.nuclei.dot.plotly <- ggplot(ki67.barplot.df, 
                               aes(x = nuclei, y = Ki_67, text = paste0("Animal_ROI: ", animal_roi))) +
                          geom_point() +
                          labs(x = "Nuclei Count", 
                               y = "Ki-67 Expression", 
                               title = "Nuclei Count by Ki-67 Expression")
# Visualize the plotly plot
ggplotly(ki67.nuclei.dot.plotly)

# Create a plot without a trend line
ki67.nuclei.dot.plot <- ggplot(ki67.barplot.df, 
                               aes(x = nuclei, y = Ki_67)) +
                          geom_point() +
                          labs(x = "Nuclei Count", 
                               y = "Ki-67 Expression", 
                               title = "Nuclei Count by Ki-67 Expression")

# Export the basic dot plot
export.dotplot <- TRUE
if(export.dotplot == TRUE){
  ggsave(paste0(project.folder.path, "results/ki67_nuclei_dotplot.png"), ki67.nuclei.dot.plot, width = 9, height = 8)
}

# Create a plot with a trend line
ki67.nuclei.dot.plot.trend <- ggplot(ki67.barplot.df, 
                               aes(x = nuclei, y = Ki_67)) +
                          geom_point() +
                          geom_smooth(method = "lm", formula = y ~ x, se = TRUE) +
                          labs(x = "Nuclei Count", 
                               y = "Ki-67 Expression", 
                               title = "Nuclei Count by Ki-67 Expression")

# Check if there is a relationship between nuclei and CD45 expression
cor.test(ki67.barplot.df$nuclei, ki67.barplot.df$Ki_67, method = "spearman")


# Boxplot for Nuclei count per ROI and CD45 expression

cd45.barplot.df$`nuclei` <- as.numeric(cd45.barplot.df$`Nuclei count`)

cd45.barplot.df$animal_roi <- paste0(cd45.barplot.df$`Animal #`, "_", cd45.barplot.df$roi)

# Create a plot labeled for plotly
cd45.nuclei.dot.plotly <- ggplot(cd45.barplot.df, 
                               aes(x = nuclei, y = CD45, text = paste0("Animal_ROI: ", animal_roi))) +
                          geom_point() +
                          labs(x = "Nuclei Count", 
                               y = "CD45 Expression", 
                               title = "Nuclei Count by CD45 Expression")
# Visualize the plotly plot
ggplotly(cd45.nuclei.dot.plot)

# Create a plot with a trend line
cd45.nuclei.dot.plot <- ggplot(cd45.barplot.df, 
                               aes(x = nuclei, y = CD45)) +
                          geom_point() + 
                          labs(x = "Nuclei Count", 
                               y = "CD45 Expression", 
                               title = "Nuclei Count by CD45 Expression")

# Export the basic dot plot
export.dotplot <- TRUE
if(export.dotplot == TRUE){
  ggsave(paste0(project.folder.path, "results/cd45_nuclei_dotplot.png"), cd45.nuclei.dot.plot, width = 9, height = 8)
}

# Create a plot with a trend line
cd45.nuclei.dot.plot.trend <- ggplot(cd45.barplot.df, 
                               aes(x = nuclei, y = CD45)) +
                          geom_point() +
                          geom_smooth(method = "lm", formula = y ~ x, se = TRUE) +
                          labs(x = "Nuclei Count", 
                               y = "CD45 Expression", 
                               title = "Nuclei Count by CD45 Expression")

# Check if there is a relationship between nuclei and CD45 expression
cor.test(cd45.barplot.df$nuclei, cd45.barplot.df$CD45, method = "spearman")





```

``` {r}
# Bar plots

# Create the bar plot
#ki67.boxplot <- ggplot(ki67.barplot.df, aes(x = treatment, y = Ki_67)) +
#  geom_boxplot(stat = "identity", 
#               outlier.colour="black", 
#               outlier.shape=16, 
#               outlier.size=2, 
#               notch=FALSE) +
#  labs(x = "age", y = "Counts", title = "Counts of Ki-67") +
#  scale_y_continuous(labels = scales::comma)

#ki67.boxplot <- ggplot(ki67.barplot.df, aes(x = treatment, y = Ki_67)) + 
#  geom_bar()
#  geom_errorbar()
  
#ggplot(data) +
#    geom_bar( aes(x=name, y=value), stat="identity", fill="skyblue", alpha=0.7) +
#    geom_errorbar( aes(x=name, ymin=value-sd, ymax=value+sd), width=0.4, colour="orange", alpha=0.9, #size=1.3)

```


## 5. Unsupervised Analysis:

```{r Unsupervised Analysis, echo=TRUE}
    
    library(gridExtra)
  
    ###
    ## House Keeping Normalization
    ###
    # Generate PCA/TSNE/UMAP:
    unsupervised.output <- dimReduct(object = norm.hk, 
                        assay.data = "hk_norm", 
                        point.size = 2.5,
                        point.alpha = 0.7, 
                        symbol.size = 1, 
                        text.size = 8, 
                        color.variable1 = "region",
                        shape.variable = "class"
    )
    
    hk_norm_pca <- unsupervised.output$plot$PCA + ggtitle("Housekeeping")
    print(unsupervised.output$plot$PCA)
    print(unsupervised.output$plot$tSNE)
    print(unsupervised.output$plot$UMAP)
    
    ggsave(file.path(paste0(results.folder, "hk_norm_pca.png")), 
           plot = unsupervised.output$plot$PCA, height = 12, width = 20)
    ggsave(file.path(paste0(results.folder, "hk_norm_tsne.png")), 
           plot = unsupervised.output$plot$tSNE, height = 12, width = 20)
    ggsave(file.path(paste0(results.folder, "hk_norm_umap.png")), 
           plot = unsupervised.output$plot$UMAP, height = 12, width = 20)
    
    ###
    ## Negative Normalization
    ###
    # Generate PCA/TSNE/UMAP:
    unsupervised.output <- dimReduct(object = norm.neg, 
                        assay.data = "neg_norm", 
                        point.size = 2.5,
                        point.alpha = 0.7, 
                        symbol.size = 1, 
                        text.size = 8, 
                        color.variable1 = "region",
                        shape.variable = "class"
    )
    
    neg_norm_pca <- unsupervised.output$plot$PCA + ggtitle("Negative")
    print(unsupervised.output$plot$PCA)
    print(unsupervised.output$plot$tSNE)
    print(unsupervised.output$plot$UMAP)
    
    
    ggsave(file.path(paste0(results.folder, "neg_norm_pca.png")), 
           plot = unsupervised.output$plot$PCA, height = 12, width = 20)
    ggsave(file.path(paste0(results.folder, "neg_norm_tsne.png")), 
           plot = unsupervised.output$plot$tSNE, height = 12, width = 20)
    ggsave(file.path(paste0(results.folder, "neg_norm_umap.png")), 
           plot = unsupervised.output$plot$UMAP, height = 12, width = 20)
    
    ###
    ## Q3 Normalization
    ###
    # Generate PCA/TSNE/UMAP:
    unsupervised.output <- dimReduct(object = norm.q3, 
                        assay.data = "q_norm", 
                        point.size = 2.5,
                        point.alpha = 0.7, 
                        symbol.size = 1, 
                        text.size = 8, 
                        color.variable1 = "region",
                        shape.variable = "class"
    )
    
    q_norm_pca <- unsupervised.output$plot$PCA + ggtitle("Quartile 3")
    print(unsupervised.output$plot$PCA)
    print(unsupervised.output$plot$tSNE)
    print(unsupervised.output$plot$UMAP)
    
    ggsave(file.path(paste0(results.folder, "q_norm_pca.png")), 
           plot = unsupervised.output$plot$PCA, height = 12, width = 20)
    ggsave(file.path(paste0(results.folder, "q_norm_tsne.png")), 
           plot = unsupervised.output$plot$tSNE, height = 12, width = 20)
    ggsave(file.path(paste0(results.folder, "q_norm_umap.png")), 
           plot = unsupervised.output$plot$UMAP, height = 12, width = 20)
    
    
  hk_norm_pca <- hk_norm_pca + theme(legend.position = "none")
  neg_norm_pca <- neg_norm_pca + theme(legend.position = "none")
  q_norm_pca <- q_norm_pca + theme(legend.position = "none")
  # Assuming plot1, plot2, and plot3 are your individual plots
  combined_pca <- grid.arrange(hk_norm_pca, neg_norm_pca, q_norm_pca, ncol = 3)

  # Save the combined plot
  ggsave(file.path(paste0(results.folder, "combined_pca.png")),
         plot = combined_pca, 
         height = 12, width = 40)

```


## 6. Clustering high CV Genes and Heatmap:

 
```{r Clustering high CV Genes, echo=TRUE}

    library(pheatmap)
    
    # Prepare the normalized counts as a df
    hk.norm.df <- as.data.frame(hk.norm_counts)
    
    # Convert dcc columns to numeric
    dcc.columns <- hk.norm.df[, -1]
    dcc.columns <- apply(dcc.columns, 2, as.numeric)
    hk.norm.df <- cbind(hk.norm.df[, 1, drop = FALSE], dcc.columns)
    
    # Convert to log counts
    log.norm.df <- log2(hk.norm.df[, -1] + 1)
    #log.norm.df <- cbind(hk.norm.df[, 1, drop = FALSE], log.norm.counts)
    
    # Set up the heatmap annotation with select columns
    
    # Columns to plot on heatmap
    anno.columns <- c("age","treatment")
    
    # Set up the annotation df using the cleaned df with NTCs removed
    cleaned.annotation.df <- as.data.frame(cleaned.annotation.df)
    rownames(cleaned.annotation.df) <- cleaned.annotation.df$Sample_ID
    
    # Subset and order the annotation for the selected columns
    # Arrange the annotations with the biggest group as the final arrange
    heatmap.annotation <- cleaned.annotation.df[ ,anno.columns]
    heatmap.annotation <- heatmap.annotation %>% 
      arrange(treatment) %>% 
      arrange(age)
    
    # Define the colors for the annotation
    anno.colors = list(
      age = c(young = "seagreen", 
              old = "salmon2"), 
      treatment = c(BLZ945 = "yellow", 
                    'IP-549' = "orange", 
                    control = "slategray")
      )
    

    # Remove the .dcc from the sample IDs in the log counts df
    colnames(log.norm.df) <- gsub("\\.dcc$", "", colnames(log.norm.df))
    
  
    # Reorder the data columns to they match the annotation row order
    
    row.order <- rownames(heatmap.annotation)
    log.norm.df <- log.norm.df[, row.order]
    
    # Make the heatmap
    heatmap.all.proteins <- pheatmap(log.norm.df, 
         main = "All Protein Signatures", 
         show_rownames = TRUE, 
         scale = "row",   
         show_colnames = FALSE,
         border_color = NA, 
         cluster_rows = TRUE, 
         cluster_cols = FALSE, 
         clustering_method = "average", 
         clustering_distance_rows = "correlation", 
         clustering_distance_cols = "correlation", 
         color = colorRampPalette(c("blue", "white", "red"))(120), 
         annotation_row = NA, 
         annotation_col = heatmap.annotation, 
         annotation_colors = anno.colors
         )
    
    # Export the heatmap
    
    export.heatmap <- TRUE
    if(export.heatmap == TRUE){
  
    ggsave(paste0(project.folder.path, "results/heatmap_all_proteins.png"),
         plot = heatmap.all.proteins, 
         width = 12, 
         height = 10, 
         units = "in")
  
    }
    
    # Make heatmap with column clustering
    
    heatmap.all.proteins.clust <- pheatmap(log.norm.df, 
         main = "All Protein Signatures", 
         show_rownames = TRUE, 
         scale = "row",   
         show_colnames = FALSE,
         border_color = NA, 
         cluster_rows = TRUE, 
         cluster_cols = TRUE, 
         clustering_method = "average", 
         clustering_distance_rows = "correlation", 
         clustering_distance_cols = "correlation", 
         color = colorRampPalette(c("blue", "white", "red"))(120), 
         annotation_row = NA, 
         annotation_col = heatmap.annotation, 
         annotation_colors = anno.colors
         )
    
    # Export the heatmap
    
    export.heatmap <- TRUE
    if(export.heatmap == TRUE){
  
    ggsave(paste0(project.folder.path, "results/heatmap_all_proteins_clust.png"),
         plot = heatmap.all.proteins.clust, 
         width = 12, 
         height = 10, 
         units = "in")
  
    }
    
    
    # Merge the counts and annotation
    merge.df <- merge(annotation, hk_counts_transposed, 
                      by.x = "row.names", by.y = "row.names")
    
    # log counts
    Biobase::assayDataElement(object = hk.norm, elt = "log_q") <-
    assayDataApply(hk.norm,
                   2,
                   FUN = log,
                   base = 2,
                   elt = "hk_norm")
  
  # create CV function
  .calcCv <- function(x) {
    sd(x) / mean(x)
  }
  cv.dat <- assayDataApply(hk.norm,
                           elt = "log_q", MARGIN = 1, .calcCv)
  
  
  # show the highest CD genes and their CV values
  sort(cv.dat, decreasing = TRUE)[1:5]
  
  # Identify genes in the top 3rd of the CV values
  goi <- names(cv.dat)[cv.dat > quantile(cv.dat, 0.8)]
  
  
  # make gene list for plot
  plot.genes <-
    Biobase::assayDataElement(hk.norm, elt = "log_q")
  
  # Annotation column to use
  anno.col <- 
    as.data.frame(annotation$class)
  
  # make plot
  p <- pheatmap(
    plot.genes,
    main = "Clustering high CV genes",
    scale = "none",
    show_rownames = TRUE,
    show_colnames = TRUE,
    border_color = NA,
    clustering_method = "average",
    cluster_rows = TRUE,
    cluster_cols = TRUE,
    clustering_distance_rows = "correlation",
    clustering_distance_cols = "correlation",
    breaks = seq(-3, 3, 0.05),
    color = colorRampPalette(c("blue", "white", "red"))(120), 
    annotation_col = anno.col
  )

    heatmap.output <- heatMap(object = hk.norm, 
                        ngenes = 200, 
                        scale.by.row.or.col = "row", 
                        show.rownames = FALSE, 
                        show.colnames = FALSE, 
                        clustering.method = "average", 
                        cluster.rows = TRUE, 
                        cluster.cols = TRUE,
                        clustering.distance.rows = "correlation", 
                        clustering.distance.cols = "correlation", 
                        annotation.row = NA, 
                        annotation.col = c("class", "slide_name"), 
                        breaks.by.values = seq(-3, 3, 0.05), 
                        heatmap.color = colorRampPalette(c("blue", "white", "red"))(120), 
                        norm.method = "hk_norm")


    print(heatmap.output$plot)
    
```


## 7. Differential Expression Analysis:


```{r Differential Expression Analysis,  echo=TRUE}


library(stats)
library(dplyr)
library(tidyr)






# Make the Sample ID as rows
counts.transposed <- as.data.frame(t(hk.norm_counts))

# Create a column for the Sample IDs and remove the .dcc
counts.transposed$Sample_ID <- rownames(counts.transposed)
counts.transposed$Sample_ID <- gsub("\\.dcc$", "", counts.transposed$Sample_ID)
rownames(counts.transposed) <- NULL


# Combine the counts with the annotation based on Sample ID
diff.eq.df <- merge(cleaned.annotation.df, counts.transposed, by = "Sample_ID")


# Old BLZ945

subset.diff.eq <- subset(diff.eq.df, age == "old" & treatment %in% c("BLZ945", "control"))

subset.diff.eq$treatment <- as.factor(subset.diff.eq$treatment)

anova_results <- sapply(colnames(subset.diff.eq)[-(1:23)], function(gene) {
  fit <- lm(get(gene) ~ treatment, data = subset.diff.eq)
  summary_fit <- summary(fit)
  p_value <- summary_fit$coefficients[2, 4]
  log_fc <- summary_fit$coefficients[2, 1]
  c(p_value, log_fc)
})

valid_genes <- complete.cases(anova_results)

# Extract p-values and log-fold changes for valid genes
p_values <- anova_results[1, valid_genes]
log_fold_changes <- anova_results[2, valid_genes]

# Extract gene IDs for valid genes
gene_ids <- names(anova_results)[valid_genes]

# Create results data frame for valid genes
old.blz945.results_df <- data.frame(
  p_value = p_values,
  log_fold_change = log_fold_changes
)

old.blz945.results_df$gene <- rownames(old.blz945.results_df)
rownames(old.blz945.results_df) <- NULL

# Adjust p-values for multiple testing
old.blz945.results_df$adjusted_p_value <- p.adjust(old.blz945.results_df$p_value, method = "fdr")

# Print first few rows of results
print(head(old.blz945.results_df))

write.csv(old.blz945.results_df, file.path(paste0(results.folder, "DE_Old_BLZ945.csv")), 
              row.names = FALSE)



# Old IP549

subset.diff.eq <- subset(diff.eq.df, age == "old" & treatment %in% c("IP-549", "control"))

subset.diff.eq$treatment <- as.factor(subset.diff.eq$treatment)

anova_results <- sapply(colnames(subset.diff.eq)[-(1:23)], function(gene) {
  fit <- lm(get(gene) ~ treatment, data = subset.diff.eq)
  summary_fit <- summary(fit)
  p_value <- summary_fit$coefficients[2, 4]
  log_fc <- summary_fit$coefficients[2, 1]
  c(p_value, log_fc)
})

valid_genes <- complete.cases(anova_results)

# Extract p-values and log-fold changes for valid genes
p_values <- anova_results[1, valid_genes]
log_fold_changes <- anova_results[2, valid_genes]

# Extract gene IDs for valid genes
gene_ids <- names(anova_results)[valid_genes]

# Create results data frame for valid genes
old.ip549.results_df <- data.frame(
  p_value = p_values,
  log_fold_change = log_fold_changes
)

old.ip549.results_df$gene <- rownames(old.ip549.results_df)
rownames(old.ip549.results_df) <- NULL

# Adjust p-values for multiple testing
old.ip549.results_df$adjusted_p_value <- p.adjust(old.ip549.results_df$p_value, method = "fdr")

# Print first few rows of results
print(head(old.ip549.results_df))

write.csv(old.ip549.results_df, file.path(paste0(results.folder, "DE_Old_IP549.csv")), 
              row.names = FALSE)


# Young BLZ945

subset.diff.eq <- subset(diff.eq.df, age == "young" & treatment %in% c("BLZ945", "control"))

subset.diff.eq$treatment <- as.factor(subset.diff.eq$treatment)

anova_results <- sapply(colnames(subset.diff.eq)[-(1:23)], function(gene) {
  fit <- lm(get(gene) ~ treatment, data = subset.diff.eq)
  summary_fit <- summary(fit)
  p_value <- summary_fit$coefficients[2, 4]
  log_fc <- summary_fit$coefficients[2, 1]
  c(p_value, log_fc)
})

valid_genes <- complete.cases(anova_results)

# Extract p-values and log-fold changes for valid genes
p_values <- anova_results[1, valid_genes]
log_fold_changes <- anova_results[2, valid_genes]

# Extract gene IDs for valid genes
gene_ids <- names(anova_results)[valid_genes]

# Create results data frame for valid genes
young.blz945.results_df <- data.frame(
  p_value = p_values,
  log_fold_change = log_fold_changes
)

young.blz945.results_df$gene <- rownames(young.blz945.results_df)
rownames(young.blz945.results_df) <- NULL

# Adjust p-values for multiple testing
young.blz945.results_df$adjusted_p_value <- p.adjust(young.blz945.results_df$p_value, method = "fdr")

# Print first few rows of results
print(head(young.blz945.results_df))

write.csv(young.blz945.results_df, file.path(paste0(results.folder, "DE_Young_BLZ945.csv")), 
              row.names = FALSE)


# Young IP549

subset.diff.eq <- subset(diff.eq.df, age == "young" & treatment %in% c("IP-549", "control"))

subset.diff.eq$treatment <- as.factor(subset.diff.eq$treatment)

anova_results <- sapply(colnames(subset.diff.eq)[-(1:23)], function(gene) {
  fit <- lm(get(gene) ~ treatment, data = subset.diff.eq)
  summary_fit <- summary(fit)
  p_value <- summary_fit$coefficients[2, 4]
  log_fc <- summary_fit$coefficients[2, 1]
  c(p_value, log_fc)
})

valid_genes <- complete.cases(anova_results)

# Extract p-values and log-fold changes for valid genes
p_values <- anova_results[1, valid_genes]
log_fold_changes <- anova_results[2, valid_genes]

# Extract gene IDs for valid genes
gene_ids <- names(anova_results)[valid_genes]

# Create results data frame for valid genes
young.ip549.results_df <- data.frame(
  p_value = p_values,
  log_fold_change = log_fold_changes
)

young.ip549.results_df$gene <- rownames(young.ip549.results_df)
rownames(young.ip549.results_df) <- NULL

# Adjust p-values for multiple testing
young.ip549.results_df$adjusted_p_value <- p.adjust(young.ip549.results_df$p_value, method = "fdr")

# Print first few rows of results
print(head(young.ip549.results_df))

write.csv(young.ip549.results_df, file.path(paste0(results.folder, "DE_Young_IP549.csv")), 
              row.names = FALSE)

```



```{r}
modelFormula = ~ class + (1 + class | slide)

model.formula <- "~ treatment"

pData(norm.hk)$treatment <- factor(pData(norm.hk)$class, c("control", "IP549", "BLZ945"))

pData(norm.hk)[["slide"]] <- factor(pData(norm.hk)[["slide_name"]])

assayDataElement(object = norm.hk, elt = "hk_norm") <-
    assayDataApply(norm.hk, 2, FUN = log, base = 2, elt = "hk_norm")

# run LMM:
# formula follows conventions defined by the lme4 package
results <- c()
for(age in c("young", "old")) {
    ind <- pData(norm.hk)$region == age
    mixedOutmc <-
        mixedModelDE(norm.hk[, ind],
                     elt = "hk_norm",
                     modelFormula = ~ treatment + (1 + treatment | 'Animal #'),
                     groupVar = "treatment",
                     nCores = parallel::detectCores(),
                     multiCore = FALSE)
    
    # format results as data.frame
    r_test <- do.call(rbind, mixedOutmc["lsmeans", ])
    tests <- rownames(r_test)
    r_test <- as.data.frame(r_test)
    r_test$Contrast <- tests
    
    # use lapply in case you have multiple levels of your test factor to
    # correctly associate gene name with it's row in the results table
    r_test$Gene <- 
        unlist(lapply(colnames(mixedOutmc),
                      rep, nrow(mixedOutmc["lsmeans", ][[1]])))
    r_test$Subset <- status
    r_test$FDR <- p.adjust(r_test$`Pr(>|t|)`, method = "fdr")
    r_test <- r_test[, c("Gene", "Subset", "Contrast", "Estimate", 
                         "Pr(>|t|)", "FDR")]
    results <- rbind(results, r_test)
}

```



```{r}


    goi <- c("CD274", "CD8A", "CD68", "EPCAM",
             "KRT18", "NPHS1", "NPHS2", "CALB1", "CLDN8")
    
    object <- q3.normalization.output$object
    object <- object[goi,]
    Gene <- Subset <- NULL
    
    #First analysis:
    reslist.1 <- diffExpr(object = object, 
                          analysis.type = "Within Groups", 
                          region.col = "region", 
                          regions = c("glomerulus", "tubule"), 
                          group.col = "class", 
                          groups = c("DKD", "normal"), 
                          n.cores = 1)
    grid.draw(reslist.1$sample_table)
    grid.newpage()
    grid.draw(reslist.1$summary_table)
    
    lfc_col1 <- colnames(reslist.1$result)[grepl("logFC",colnames(reslist.1$result))]
    pval_col1 <- colnames(reslist.1$result)[grepl("_pval",colnames(reslist.1$result))]
    
    lfc.1 <- reslist.1$result %>% 
              dplyr::filter(Gene == "CALB1" & Subset == "normal") %>% 
              select(all_of(lfc_col1)) %>% 
              as.numeric()
    pval.1 <- reslist.1$result %>% 
              dplyr::filter(Gene == "CALB1" & Subset == "normal") %>% 
              select(all_of(pval_col1)) %>% 
              as.numeric()
    
    cat(paste0("\n\nvalue of CALB Fold Change is:", lfc.1))
    cat("expected value is -2.014")
    
    cat(paste0("\nvalue of CALB pval is:",pval.1))
    cat("expected value is 0.0274")
    
    #Second analysis:
    reslist.2 <- diffExpr(object = object, 
                          analysis.type = "Between Groups", 
                          region.col = "region", 
                          regions = c("glomerulus", "tubule"), 
                          group.col = "class", 
                          groups = c("DKD", "normal"), 
                          n.cores = 1)
    grid.draw(reslist.2$sample_table)
    grid.newpage()
    grid.draw(reslist.2$summary_table)
    
    lfc_col2 <- colnames(reslist.2$result)[grepl("logFC",colnames(reslist.2$result))]
    pval_col2 <- colnames(reslist.2$result)[grepl("_pval",colnames(reslist.2$result))]
    
    lfc.2 <- reslist.2$result %>% 
              dplyr::filter(Gene == "CALB1" & Subset == "tubule") %>% 
              select(all_of(lfc_col2)) %>% 
              as.numeric()
    pval.2 <- reslist.2$result %>% 
              dplyr::filter(Gene == "CALB1" & Subset == "tubule") %>% 
              select(all_of(pval_col2)) %>% 
              as.numeric()
    
    cat(paste0("\n\nvalue of CALB Fold Change is:", lfc.2))
    cat("expected value is -1.408")
    
    cat(paste0("\nvalue of CALB pval is:",pval.2))
    cat("expected value is 0.01268")
    

```
## 8. Volcano Plot

#This part is run on NIDAP.

## 9. Violin Plot

```{r Violin Plot, echo=TRUE}
    
    genes <- c("CD274", "CD8A", "CD68", "EPCAM",
         "KRT18", "NPHS1", "NPHS2", "CALB1", "CLDN8")
    
    violin.plot.test <- violinPlot(object = q3.normalization.output$object, 
                                        expr.type = "q_norm", 
                                        genes = genes,
                                        group = "region",
                                        facet.by = "segment")
    grid.arrange(violin.plot.test)

```
